// <auto-generated />
using System;
using OnlineAkademi.Data.Sql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace OnlineAkademi.Data.Sql.Migrations
{
    [DbContext(typeof(AkademiContext))]
    [Migration("20210529115200_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OnlineAkademi.Core.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("1");

                    b.Property<DateTime>("LastupDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("LastupUser")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("CategoryName");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2021, 5, 29, 14, 51, 59, 476, DateTimeKind.Local).AddTicks(4223),
                            CreateUser = "admin",
                            LastupDate = new DateTime(2021, 5, 29, 14, 51, 59, 477, DateTimeKind.Local).AddTicks(6750),
                            LastupUser = "admin",
                            Name = "Kategori 1"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2021, 5, 29, 14, 51, 59, 477, DateTimeKind.Local).AddTicks(7658),
                            CreateUser = "admin",
                            LastupDate = new DateTime(2021, 5, 29, 14, 51, 59, 477, DateTimeKind.Local).AddTicks(7665),
                            LastupUser = "admin",
                            Name = "Kategori 2"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2021, 5, 29, 14, 51, 59, 477, DateTimeKind.Local).AddTicks(7669),
                            CreateUser = "admin",
                            LastupDate = new DateTime(2021, 5, 29, 14, 51, 59, 477, DateTimeKind.Local).AddTicks(7670),
                            LastupUser = "admin",
                            Name = "Kategori 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
