// <auto-generated />
using System;
using OnlineAkademi.Data.Sql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace OnlineAkademi.Data.Sql.Migrations
{
    [DbContext(typeof(IlknurContext))]
    partial class IlknurContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OnlineAkademi.Core.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("1");

                    b.Property<DateTime>("LastupDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("LastupUser")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("CategoryName");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2021, 6, 12, 15, 51, 40, 227, DateTimeKind.Local).AddTicks(1654),
                            CreateUser = "admin",
                            LastupDate = new DateTime(2021, 6, 12, 15, 51, 40, 228, DateTimeKind.Local).AddTicks(2599),
                            LastupUser = "admin",
                            Name = "Kategori 1"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2021, 6, 12, 15, 51, 40, 228, DateTimeKind.Local).AddTicks(3327),
                            CreateUser = "admin",
                            LastupDate = new DateTime(2021, 6, 12, 15, 51, 40, 228, DateTimeKind.Local).AddTicks(3332),
                            LastupUser = "admin",
                            Name = "Kategori 2"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2021, 6, 12, 15, 51, 40, 228, DateTimeKind.Local).AddTicks(3335),
                            CreateUser = "admin",
                            LastupDate = new DateTime(2021, 6, 12, 15, 51, 40, 228, DateTimeKind.Local).AddTicks(3336),
                            LastupUser = "admin",
                            Name = "Kategori 3"
                        });
                });

            modelBuilder.Entity("OnlineAkademi.Core.Domain.Entities.Error", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Exception")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<bool>("IsAjaxRequest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<string>("QueryString")
                        .HasColumnType("varchar(200)");

                    b.Property<int>("RequestType")
                        .HasColumnType("int");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Errors");
                });

            modelBuilder.Entity("OnlineAkademi.Core.Domain.Entities.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("LogDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("New")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Old")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("CrudLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
